name: usteer CI

on:
  push:
    branches-ignore:
      - '*Doc*'
      - '*doc*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      sdk_name: "openwrt-sdk"
      sdk_version: "gcc-8.4.0_musl.Linux-x86_64" 
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: WDR4300
            ARCH: "ath79"
            MODEL: "generic"
          - name: RPi_3B_plus
            ARCH: "bcm27xx"
            MODEL: "bcm2710"

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: |
        cd ..
        SDK_FILE="${{ env.sdk_name }}-${{ matrix.ARCH }}-${{ matrix.MODEL }}_${{ env.sdk_version }}"
        wget "https://downloads.openwrt.org/snapshots/targets/${{ matrix.ARCH }}/${{ matrix.MODEL }}/${SDK_FILE}.tar.xz"
        tar -xf "${SDK_FILE}.tar.xz"
        cd "${SDK_FILE}/"
        cp feeds.conf.default feeds.conf
        echo "src-link usteer `realpath $PWD/../usteer`" >> feeds.conf
        ./scripts/feeds update base packages usteer
        ./scripts/feeds install usteer
        make defconfig
        echo "CONFIG_FEED_usteer=y" >> .config
        make package/usteer/download
        make package/usteer/prepare
        make -j1 V=sc package/usteer/compile
        mv bin/ ../usteer/actions-output/
    - uses: actions/upload-artifact@v2
      with:
        name: usteer-package-${{ matrix.name }}
        path: "actions-output/packages/*/usteer/usteer*.ipk"
